# Site settings
title: Reproducible Research
email: jwbomt@gmail.com
description: "Tips, tricks, and thoughts on reproducible research in genetics and genomics."
baseurl: "/reproducible_research"
github_username:  jwbomt

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]

pages_list:       
  Archive: '/archive'