# Dependencies
markdown:         redcarpet
highlights:         true

# Permalinks
permalink:        pretty

# Setup
title:            Reproducible Research
tagline:          'Reproducible research in genetics'
description:      'Base theme for Jekyll themes by @mdo.'
url: http://jwbomt.github.io
baseurl:         reproducible_research
author:
  name:           'Jonathan Chung'

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/jwbomt/jwbomt.github.io

# This is the list of pages to include in the header of the website.
pages_list:       
    About: '{{ site.baseurl }}/about'
    Archive: '{{ site.baseurl }}/archive'
    Feed: '{{ site.baseurl }}/atom.xml'
